// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "monkey":return img`
. . . . . . . f f f f f . . . . 
. . . . . . f e e e e e f . . . 
. . . . . f e e e d d d d f . . 
. . . . f f e e d f d d f d c . 
. . . f d d e e d f d d f d c . 
. . . c d b e e d d d d e e d c 
f f . c d b e e d d c d d d d c 
f e f . c f e e d d d c c c c c 
f e f . . f f e e d d d d d f . 
f e f . f e e e e f f f f f . . 
f e f f e e e e e e e f . . . . 
. f f e e e e f e f f e f . . . 
. . f e e e e f e f f e f . . . 
. . . f e f f b d f b d f . . . 
. . . f d b b d d c d d f . . . 
. . . f f f f f f f f f . . . . 
`;
            case "image4":
            case "myImage1":return img`
. . . . . . f f f f f . . . . . 
. . . . . f e e e e e f f . . . 
. . . . f d d d d e e e f f . . 
. . . . f d f d d e e e d d f . 
. . . f e d f d d e e e d d f . 
. . . f d d d d d e e e b d f . 
. . . c d d c d e e e e b f f f 
. . . c c c d d e e e f f f d d 
. . . . . f f e e e e f e e d d 
. . . . . . . f e e e e e e b d 
. f f f . . f f e e e e f f f f 
. f e e f . f e e e e f f e e f 
. . f e f f f e e e e e e e f f 
. . f e e e f e e e e f e e d f 
. . . f f f f f e e e f f c d f 
. . . . . . . f f f f . f f f f 
`;
            case "image2":
            case "myImage":return img`
. . . . . . . f f f f f . . . . 
. . . . . . f e e e e e f . . . 
. . . . . f d d d d e e e f . . 
. . . . c d f d d f d e e f . . 
. . . . c d f d d f d e e f f . 
. . . c d e e d d d d e e d d f 
. . . c d d d d c d d e e b d c 
. . . c c c c c d d e e e b f f 
. . . . f d d d d e e e f f d d 
. . . . . f f f f f e e e e d d 
. . f f . . . f e e e e e e b d 
. . f e f . f f e e e e f f f f 
. . f e f . f e e e e f f d d f 
. . f e f f f e e e e e e c d f 
. . f e e e f f e e e f e c d f 
. . . f f f f f f f f f f f f f 
`;
            case "image5":
            case "myImage2":return img`
. . . . . f f f f f . . . . . . 
. . . . f e e e e e f . . . . . 
. . . f d d d d d e e f . . . . 
. . f f f d d f f d e f f . . . 
. c d d e e d d d d e d d f . . 
. c c d d d d c d d e d f f f . 
. c d c c c c d d d e d f b d f 
. . c d d d d d d e e f f d d f 
. . . c d d d d e e f f e f f f 
. . . . f f f e e f e e e f . . 
. . . . f e e e e e e e f f f . 
. . . f e e e e e e f f f e f . 
. . f f e e e e f f f f f e f . 
. f b d f e e f b b f f f e f . 
. f d d f e e f d d b f f f f . 
. f f f f f f f f f f f f f . . 
`;
            case "image6":
            case "myImage3":return img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . 8 8 8 8 8 8 8 . . . . 
. . 8 8 7 7 7 7 7 7 7 8 8 . . 
. 8 8 7 6 6 8 8 8 6 6 7 8 8 . 
. 8 7 6 6 8 8 7 8 8 6 6 7 8 . 
. 8 6 6 8 8 8 8 8 8 8 6 6 8 . 
. c 8 6 8 6 7 7 7 6 8 6 8 c . 
c c 8 8 6 6 6 6 6 6 6 8 8 c c 
c d c c 8 8 8 8 8 8 8 c c d c 
c d d d c c c c c c c d d d c 
c c b d d d d d d d d d b c c 
c c c c c b b b b b c c c c c 
c c b b b b b b b b b b b c c 
. c c b b b b b b b b b c c . 
. . . c c c c c c c c c . . . 
`;
            case "image8":
            case "myImage5":return img`
. f f f f f f f f f f f f f f . 
f f b b b b b b b b b b b b f f 
f f d d d d d d d d d d d d f f 
. f f f f f f f f f f f f f f . 
. . f b b b b b b b b b b f . . 
. . f d d d d d d d d d d b f . 
. f b d c c d c c d c c d d f . 
. . f d d c c c d d d d d f . . 
. . f d d c d c d c c d d b f . 
. f b d d d d d d c c d d d f . 
. f d d d c c d c c d d c f . . 
. . f d d d d d d c d d d f . . 
. f f f f f f f f f f f f f f . 
f f d d d d d d d d d d d d f f 
f f b b b b b b b b b b b b f f 
. f f f f f f f f f f f f f f . 
`;
            case "image7":
            case "myImage4":return img`
..55555555555555..
.5ffffffffffffff5.
5ffbbbbbbbbbbbbff5
5ffddddddddddddff5
.5ffffffffffffff5.
..5fbbbbbbbbbbf5..
..5fddddddddddbf5.
.5fbdccdccdccddf5.
..5fddcccdddddf5..
..5fddcdcdccddbf5.
.5fbddddddccdddf5.
.5fdddccdccddcf5..
..5fddddddcdddf5..
.5ffffffffffffff5.
5ffddddddddddddff5
5ffbbbbbbbbbbbbff5
.5ffffffffffffff5.
..55555555555555..
`;
            case "image9":
            case "myImage6":return img`
........................
...........66...........
..........6776..........
..........6776..........
.........877778.........
........86777768........
.......6777777776.......
......677677776776......
......866777777668......
.....86677677677668.....
....8668866766888668....
....8888668886686888....
.....86868868868668.....
....866888668888868.....
....8688886888888888....
....8886688888866888....
....8676888868886768....
...87778868678688776....
..8777767767787767778...
.877767777777677776778..
.8866777777777777776778.
.8667776776767776777688.
..887766768668776667668.
..8688668886688686688668
.86688688686866888688888
8668868866888866888868..
88886686688888868688668.
.8688888888888888668868.
.8878888868868878868788.
.87768776788778777667788
877677767787776767776778
88877787766777777877788.
..88886786777667768888..
.....86887786668868.....
......8886888668888.....
.........88ee88.........
.........feeeef.........
.........feeeef.........
........feeefeef........
........fefeffef........
`;
            case "image13":
            case "myImage10":return img`
................................................................................
................................................................................
................................................................................
................................................................................
........22222.............ddd......dddd...dddd.dd.................44444.........
.......2222222............ddd......dddd...dddd.dd................4444444........
.......2d22222...........ddddd....ddddd..ddddd.dd................4d44444........
.......2d22222...........ddddd....ddd....ddd.....................4dd4444........
.......2222222...........dd.dd...dddddd.dddddd.dd..ddddd.........4dd4444........
.......2222222...........dd.dd...dddddd.dddddd.dd..ddddd.........4444444........
.......2222222..........ddd.ddd..dddddd.dddddd.dd.ddd............4444444........
........22222...........ddddddd...ddd....ddd...dd.ddddd..........4444444........
..........2.............ddddddd...ddd....ddd...dd..dddd...........4444..........
..........b............ddd...ddd..ddd....ddd...dd.....dd...........44...........
..........b............ddd...ddd..ddd....ddd...dd..ddddd............4...........
..........b............ddd...ddd..ddd....ddd...dd..ddddd............4...........
.........b..........................................................4...........
.........b..........................................................4...........
.........b..........................................................4...........
........b............................................................4..........
........b............................................................4..........
.....................................................................4..........
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
.......................5............5...........................................
......................555..........555..........................................
......................525..........525..........................................
.......................2............2...........................................
.......................9............9..............eeeeeee......................
.......................3............3.............eeeeeeeee.....................
....................3449............9............eeddeeeddee....................
...................3344944..........9443.........eddddddddde....................
...................344444444......4444433......ddeddfdddfddedd..................
...................3dddddddd....444444443.....dddeddfdddfddeddd.................
...................3dddddddd....dddddddd3.....dddeddddfddddeddd.................
...................344444444....dddddddd3......ddedfdddddfdedd..................
...................3dddddddd....444444443........eddfffffdde....................
...................3dddddddd....dddddddd3.........eddddddde.....................
................................dddddddd3..........eeeeeeee.....................
..................................................eeeeeeeeee....................
.................................................eeeeeeeeeee....................
...........3....................................eeeeeeeee.ee....................
..........3344..................................eee.eeeee.ee....................
..........34444.................................edddeeee.eee....................
..........344dd44...............................eddd.ee.eeee..e.................
..........344dd4dd..............................eddd.ee.dde..ee.................
.................................................ddd.ee.dde.ee..................
................................................................................
................................................................................
`;
            case "image11":
            case "myImage8":return img`
.....fff..............fff..fff............
....f111ff.......fff..f4f..f4f............
...f111111f......f44f..f..ffff............
..f91111111f.....f45f.f4ff4f..............
..f911111111f.....f5ff554f4f..............
..f991111111f.....f44515544f..............
..f9911111111f.....f4511554f......fff.....
..f9999111111f....ff4555554f.....ffff.....
...f9199111119f...ffffffffff....ff........
...ff919911119f...f555fff55f...ff.........
....f9119911119f.f5555555555f.ff..........
.....f999991119ff555fff555554ff...........
......ff9999119f455ff1ff5555ff1f..........
.......fff99999f455ff1ff5555ff1f..........
....ffffffff999f455fffff5555ffff..........
...f9911999fff9f455fffff5555ffff..........
..ff111111199fff455fffff5555ffff..........
.ff111111111999f4455fff555555fff..........
ff1111111111999f44555555555554f...........
f9111111119999fff445555555554f............
f99911119999ffff4f44455555554f............
f9999999999ffeef44ff44444444f.............
.f99999999f4feeff444ffffffff..............
..fffffffff4ffeef454444444f...............
.........f444feeff55555544fffff...........
........ff455ffeefff55554fffffff..........
........ff4455ffefffffffffff..fff.........
........fff4555fffffffffff....fff.........
........fffff5555fffffffff.....fff........
........fffff55555fffffffffff...ff........
........f4fffff55555ffffffffff..ff........
........f444fffff554444fff.fff............
........ff444fffffff44ff...fff............
.........ff444ffffffffff...fff............
.........ffff4444fffff.....ff.............
..........fffffffffff.....................
..........fffffffff.......................
..........ffff............................
..........fff.............................
..........ff..............................
..........................................
..........................................
`;
            case "image14":
            case "myImage11":return img`
............fff..fff..............fff.....
............f4f..f4f..fff.......ff111f....
............ffff..f..f44f......f111111f...
..............f4ff4f.f54f.....f11111119f..
..............f4f455ff5f.....f111111119f..
..............f44551544f.....f111111199f..
.....fff......f4551154f.....f1111111199f..
.....ffff.....f4555554ff....f1111119999f..
........ff....ffffffffff...f9111119919f...
.........ff...f55fff555f...f911119919ff...
..........ff.f5555555555f.f9111199119f....
...........ff455555fff555ff911199999f.....
..........f1ff5555ff1ff554f9119999ff......
..........f1ff5555ff1ff554f99999fff.......
..........ffff5555fffff554f999ffffffff....
..........ffff5555fffff554f9fff9991199f...
..........ffff5555fffff554fff991111111ff..
..........fff555555fff5544f999111111111ff.
...........f45555555555544f9991111111111ff
............f455555555544fff9999111111119f
............f45555555444f4ffff99991111999f
.............f44444444ff44feeff9999999999f
..............ffffffff444ffeef4f99999999f.
...............f444444454feeff4fffffffff..
...........fffff44555555ffeef444f.........
..........fffffff45555fffeeff554ff........
.........fff..fffffffffffeff5544ff........
.........fff....fffffffffff5554fff........
........fff.....fffffffff5555fffff........
........ff...fffffffffff55555fffff........
........ff..ffffffffff55555fffff4f........
............fff.fff444455fffff444f........
............fff...ff44fffffff444ff........
............fff...ffffffffff444ff.........
.............ff.....fffff4444ffff.........
.....................fffffffffff..........
.......................fffffffff..........
............................ffff..........
.............................fff..........
..............................ff..........
..........................................
..........................................
`;
            case "image15":
            case "myImage12":return img`
..........................................
..........................................
..........................................
..........................................
..........................................
.................fff......................
...........fff...f4f...fff......fffffff...
...........f4f....f...f44f.....ff111199f..
...........fffffff4ffff54f....f111199999f.
.............f44455154fff....f11119919999f
..............f4551154f.....f111199199999f
..............f4555554ff...f1111991199999f
............fffffffffffff.ff111999999999ff
........fffff455555ff5555ff911999999999ff.
.......ff..fff5555ff1f5554f99999999999ff..
......ff..ff1ff555ff1ff554f9999ffffffff...
....fff...ff1ff555fffff554f99fff9991199f..
....fff....fff55555fff5554ffff991111111f..
...........f55555555555554f9999111111111f.
...........f55555555555544f99991111111111f
...........f45555555555544fff999911111111f
......ff....f45fff5555544ffffff9999111199f
......ffff..f4f555f55444f4feeeff999999999f
......ffffffff44444444ff44feeef4f99999999f
.........fffffffffffff444ffeeff4fffffffff.
............fffff45555fffeefff44f.........
..............fffffffffffeff5544ff........
................fffffffffff5554fff........
................fffffffff5555fffff........
...............fffffffff55555fffff........
.............fffffffff55555fffff4f........
............fff.fff444455fffff444f........
..........ffff....ff44fffffff444ff........
..........fff.....ffffffffff444ff.........
..........ff........fffff4444ffff.........
.....................ffffffffffff.........
.......................ffffffffff.........
............................ffff..........
............................fff...........
..........................................
..........................................
..........................................
`;
            case "image16":
            case "myImage13":return img`
..........................................
..........................................
..........................................
..........................................
..........................................
......................fff.................
...fffffff......fff...f4f...fff...........
..f991111ff.....f44f...f....f4f...........
.f999991111f....f45ffff4fffffff...........
f99991991111f....fff45155444f.............
f999991991111f.....f4511554f..............
f9999911991111f...ff4555554f..............
ff999999999111ff.fffffffffffff............
.ff999999999119ff5555ff555554fffff........
..ff99999999999f4555f1ff5555fff..ff.......
...ffffffff9999f455ff1ff555ff1ff..ff......
..f9911999fff99f455fffff555ff1ff...fff....
..f111111199ffff4555fff55555fff....fff....
.f1111111119999f45555555555555f...........
f11111111119999f44555555555555f...........
f111111119999fff44555555555554f...........
f9911119999ffffff4455555fff54f....ff......
f999999999ffeeef4f44455f555f4f..ffff......
f99999999f4feeef44ff44444444ffffffff......
.fffffffff4ffeeff444fffffffffffff.........
.........f44fffeefff55554fffff............
........ff4455ffefffffffffff..............
........fff4555fffffffffff................
........fffff5555fffffffff................
........fffff55555fffffffff...............
........f4fffff55555fffffffff.............
........f444fffff554444fff.fff............
........ff444fffffff44ff....ffff..........
.........ff444ffffffffff.....fff..........
.........ffff4444fffff........ff..........
.........ffffffffffff.....................
.........ffffffffff.......................
..........ffff............................
...........fff............................
..........................................
..........................................
..........................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "facing left":
            case "anim2":return [img`
. . . . f f f f f . . . . . . . 
. . . f e e e e e f . . . . . . 
. . f d d d d e e e f . . . . . 
. c d f d d f d e e f f . . . . 
. c d f d d f d e e d d f . . . 
c d e e d d d d e e b d c . . . 
c d d d d c d d e e b d c . . . 
c c c c c d d e e e f c . . . . 
. f d d d d e e e f f . . . . . 
. . f f f f f e e e e f . . . . 
. . . . f f e e e e e e f . f f 
. . . f e e f e e f e e f . e f 
. . f e e f e e f e e e f . e f 
. f b d f d b f b b f e f f e f 
. f d d f d d f d d b e f f f f 
. . f f f f f f f f f f f f f . 
`];
            case "facing right":
            case "anim3":return [img`
. . . . . . . f f f f f . . . . 
. . . . . . f e e e e e f . . . 
. . . . . f e e e d d d d f . . 
. . . . f f e e d f d d f d c . 
. . . f d d e e d f d d f d c . 
. . . c d b e e d d d d e e d c 
. . . c d b e e d d c d d d d c 
. . . . c f e e e d d c c c c c 
. . . . . f f e e e d d d d f . 
. . . . f e e e e f f f f f . . 
f f . f e e e e e e f f . . . . 
f e . f e e f e e f e e f . . . 
f e . f e e e f e e f e e f . . 
f e f f e f b b f b d f d b f . 
f f f f e b d d f d d f d d f . 
. f f f f f f f f f f f f f . . 
`];
            case "malking_left":
            case "anim4":return [img`
. . . . f f f f f . . . . . . . 
. . . f e e e e e f . . . . . . 
. . f d d d d e e e f . . . . . 
. c d f d d f d e e f f . . . . 
. c d f d d f d e e d d f . . . 
c d e e d d d d e e b d c . . . 
c d d d d c d d e e b d c . f f 
c c c c c d d d e e f c . f e f 
. f d d d d d e e f f . . f e f 
. . f f f f f e e e e f . f e f 
. . . . f e e e e e e e f f e f 
. . . f e f f e f e e e e f f . 
. . . f e f f e f e e e e f . . 
. . . f d b f d b f f e f . . . 
. . . f d d c d d b b d f . . . 
. . . . f f f f f f f f f . . . 
`, img`
. . . . f f f f f . . . . . . . 
. . . f e e e e e f . . . . . . 
. . f d d d d e e e f . . . . . 
. c d f d d f d e e f . . . . . 
. c d f d d f d e e f f . . . . 
c d e e d d d d e e d d f . . . 
c d d d d c d d e e b d c . . . 
c c c c c d d e e e b d c . f f 
. f d d d d e e e f f c . f e f 
. f f f f f f e e e e f . f e f 
. f f f f e e e e e e e f f e f 
f d d f d d f e f e e e e f f . 
f d b f d b f e f e e e e f . . 
f f f f f f f f f f f f e f . . 
. . . . . . . . . f c d d f . . 
. . . . . . . . . . f f f f . . 
`, img`
. . . . f f f f f . . . . . . . 
. . . f e e e e e f . . . . . . 
. . f d d d d e e e f f . . . . 
. c d d d d d d e e d d f . . . 
. c d f d d f d e e b d c . . . 
c d d f d d f d e e b d c . f f 
c d e e d d d d e e f c . f e f 
c d d d d c d e e e f . . f e f 
. f c c c d e e e f f . . f e f 
. . f f f f f e e e e f . f e f 
. . . . f e e e e e e e f f f . 
. . f f e f e e f e e e e f . . 
. f e f f e e f f f e e e f . . 
f d d b d d c f f f f f f b f . 
f d d c d d d f . . f c d d f . 
. f f f f f f f . . . f f f . . 
`, img`
. . . . f f f f f . . . . . . . 
. . . f e e e e e f f f . . . . 
. . f d d d e e e e d d f . . . 
. c d d d d d e e e b d c . . . 
. c d d d d d d e e b d c . . . 
c d d f d d f d e e f c . f f . 
c d d f d d f d e e f . . f e f 
c d e e d d d d e e f . . f e f 
. f d d d c d e e f f . . f e f 
. . f f f d e e e e e f . f e f 
. . . . f e e e e e e e f f f . 
. . . . f f e e e e e b f f . . 
. . . f e f f e e c d d f f . . 
. . f d d b d d c f f f . . . . 
. . f d d c d d d f f . . . . . 
. . . f f f f f f f . . . . . . 
`, img`
. . . . f f f f f . . . . . . . 
. . . f e e e e e f . . . . . . 
. . f d d d d e e e f . . . . . 
. c d f d d f d e e f f . . . . 
. c d f d d f d e e d d f . . . 
c d e e d d d d e e b d c . . . 
c d d d d c d d e e b d c . . . 
c c c c c d d e e e f c . . . . 
. f d d d d e e e f f . . . . . 
. . f f f f f e e e e f . . . . 
. . . . f f e e e e e e f . f f 
. . . f e e f e e f e e f . e f 
. . f e e f e e f e e e f . e f 
. f b d f d b f b b f e f f e f 
. f d d f d d f d d b e f f f f 
. . f f f f f f f f f f f f f . 
`];
            case "walking_right":
            case "anim1":return [img`
. . . . . . . f f f f f . . . . 
. . . . . . f e e e e e f . . . 
. . . . . f e e e d d d d f . . 
. . . . f f e e d f d d f d c . 
. . . f d d e e d f d d f d c . 
. . . c d b e e d d d d e e d c 
f f . c d b e e d d c d d d d c 
f e f . c f e e d d d c c c c c 
f e f . . f f e e d d d d d f . 
f e f . f e e e e f f f f f . . 
f e f f e e e e e e e f . . . . 
. f f e e e e f e f f e f . . . 
. . f e e e e f e f f e f . . . 
. . . f e f f b d f b d f . . . 
. . . f d b b d d c d d f . . . 
. . . f f f f f f f f f . . . . 
`, img`
. . . . . . . f f f f f . . . . 
. . . . . . f e e e e e f . . . 
. . . . . f e e e d d d d f . . 
. . . . . f e e d f d d f d c . 
. . . . f f e e d f d d f d c . 
. . . f d d e e d d d d e e d c 
. . . c d b e e d d c d d d d c 
f f . c d b e e e d d c c c c c 
f e f . c f f e e e d d d d f . 
f e f . f e e e e f f f f f f . 
f e f f e e e e e e e f f f f . 
. f f e e e e f e f d d f d d f 
. . f e e e e f e f b d f b d f 
. . f e f f f f f f f f f f f f 
. . f d d c f . . . . . . . . . 
. . f f f f . . . . . . . . . . 
`, img`
. . . . . . . f f f f f . . . . 
. . . . . . f e e e e e f . . . 
. . . . f f e e e d d d d f . . 
. . . f d d e e d d d d d d c . 
. . . c d b e e d f d d f d c . 
f f . c d b e e d f d d f d d c 
f e f . c f e e d d d d e e d c 
f e f . . f e e e d c d d d d c 
f e f . . f f e e e d c c c f . 
f e f . f e e e e f f f f f . . 
. f f f e e e e e e e f . . . . 
. . f e e e e f e e f e f f . . 
. . f e e e f f f e e f f e f . 
. f b f f f f f f c d d b d d f 
. f d d c f . . f d d d c d d f 
. . f f f . . . f f f f f f f . 
`, img`
. . . . . . . f f f f f . . . . 
. . . . f f f e e e e e f . . . 
. . . f d d e e e e d d d f . . 
. . . c d b e e e d d d d d c . 
. . . c d b e e d d d d d d c . 
. f f . c f e e d f d d f d d c 
f e f . . f e e d f d d f d d c 
f e f . . f e e d d d d e e d c 
f e f . . f f e e d c d d d f . 
f e f . f e e e e e d f f f . . 
. f f f e e e e e e e f . . . . 
. . f f b e e e e e f f . . . . 
. . f f d d c e e f f e f . . . 
. . . . f f f c d d b d d f . . 
. . . . . f f d d d c d d f . . 
. . . . . . f f f f f f f . . . 
`, img`
. . . . . . . f f f f f . . . . 
. . . . . . f e e e e e f . . . 
. . . . . f e e e d d d d f . . 
. . . . f f e e d f d d f d c . 
. . . f d d e e d f d d f d c . 
. . . c d b e e d d d d e e d c 
. . . c d b e e d d c d d d d c 
. . . . c f e e e d d c c c c c 
. . . . . f f e e e d d d d f . 
. . . . f e e e e f f f f f . . 
f f . f e e e e e e f f . . . . 
f e . f e e f e e f e e f . . . 
f e . f e e e f e e f e e f . . 
f e f f e f b b f b d f d b f . 
f f f f e b d d f d d f d d f . 
. f f f f f f f f f f f f f . . 
`];
            case "myAnim":
            case "anim5":return [img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f f . . . . 
. . . . f 1 1 1 f 1 1 1 f . . . 
. . . . f 1 1 1 1 1 1 1 f . . . 
. . . . . . 1 1 f 1 1 . . . . . 
. . . . . f f f f f f f . . . . 
. . . . f 5 5 5 f 5 5 5 f . . . 
. . . . f f 5 5 f 5 5 f f . . . 
. . . . f 5 5 5 f 5 5 5 f . . . 
. . . . . f f f f f f f . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . f f . . . . . . . . . f f . 
. f 1 1 f . f f f f f . f 1 1 f 
. f 1 1 1 f 5 5 f 5 5 f 1 1 1 f 
. f 1 1 f f f 5 f 5 f f f 1 1 f 
. . f . . f 5 5 f 5 5 f . . f . 
. . . . . . 5 5 f 5 5 . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "myAnim1":
            case "anim7":return [img`
. . . . . . . f f f f f . . . . 
. . . . . . f e e e e e f . . . 
. . . . . f d d d d e e e f . . 
. . . . c d f d d f d e e f . . 
. . . . c d f d d f d e e f f . 
. . . c d e e d d d d e e d d f 
. . . c d d d d c d d e e b d c 
. . . c c c c c d d e e e b f f 
. . . . f d d d d e e e f f d d 
. . . . . f f f f f e e e e d d 
. . f f . . . f e e e e e e b d 
. . f e f . f f e e e e f f f f 
. . f e f . f e e e e f f d d f 
. . f e f f f e e e e e e c d f 
. . f e e e f f e e e f e c d f 
. . . f f f f f f f f f f f f f 
`];
            case "myAnim2":
            case "anim8":return [img`
. . . . f f f f f . . . . . . . 
. . . f e e e e e f . . . . . . 
. . f e e e d d d d f . . . . . 
. . f e e d f d d f d c . . . . 
. f f e e d f d d f d c . . . . 
f d d e e d d d d e e d c . . . 
c d b e e d d c d d d d c . . . 
f f b e e e d d c c c c c . . . 
d d f f e e e d d d d f . . . . 
d d e e e e f f f f f . . . . . 
d b e e e e e e f . . . f f . . 
f f f f e e e e f f . f e f . . 
f d d f f e e e e f . f e f . . 
f d c e e e e e e f f f e f . . 
f d c e f e e e f f e e e f . . 
f f f f f f f f f f f f f . . . 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
